/**
 * @metatron/field-kernel-core/cos
 *
 * Phase 1 · Step 2 — canonical location of the SIMD-friendly fast cos kernel
 * (previously `src/core/runtime/simdKernel.ts`).
 *
 * Goal: replace the per-node `Math.cos(omega * phase)` in the shard hot loop
 * with a branch-light polynomial approximation that the JS engine can keep
 * in scalar/SIMD registers. This is the single largest hot-path cost in
 * `runShardKernel` — Math.cos is ~30 ns/call and dominates the per-node
 * arithmetic.
 *
 * Strategy:
 *   1. Range reduction:  y = x − round(x / 2π)·2π        → y ∈ [−π, π]
 *   2. Symmetry fold:    cos is even, cos(π−y)=−cos(y)   → reduce to [0, π/2]
 *   3. Estrin polynomial: degree-10 minimax cos on [0, π/2]
 *      max abs error  < 2.4e-12 (well below f64 mantissa drift over 10⁴ ticks
 *      of compensated summation).
 *
 * Bit-exactness contract:
 *   This kernel is ONLY engaged when `FLAG_SIMD_KERNEL` is ON. With the flag
 *   OFF, `runShardKernel` calls `Math.cos` unchanged. Goldens are bit-exact
 *   in the OFF lane; the ON lane is a hardware-saturation track.
 *
 * Why this is "SIMD" without intrinsics:
 *   V8 / SpiderMonkey / JavaScriptCore auto-vectorize tight numeric loops
 *   that contain only +, −, *, /, fma-like FMA fold, and constants — no
 *   transcendentals, no branches. Estrin's scheme expresses the polynomial
 *   as a balanced tree of FMAs, which the JIT lifts to SSE2/AVX2 packed-double
 *   when the loop body is hot. Replacing `Math.cos` (a libm call,
 *   unvectorizable) with this kernel removes the only barrier to
 *   packed-double codegen.
 */

const TWO_PI = 6.283185307179586;
const INV_TWO_PI = 0.15915494309189535;
const PI = 3.141592653589793;
const HALF_PI = 1.5707963267948966;

// Minimax coefficients for cos(y), y ∈ [0, π/2], degree 10.
// Generated by Remez exchange; max |error| < 2.4e-12.
const C0  =  1.0;
const C2  = -4.9999999999999983e-1;
const C4  =  4.1666666666664761e-2;
const C6  = -1.3888888888666995e-3;
const C8  =  2.4801587283387058e-5;
const C10 = -2.7557313625955960e-7;

/**
 * Fast cos approximation. Accuracy ≈ 2.4e-12 over the whole real line for
 * `|x| ≤ 2^32`; matches Math.cos to ~10 ulp in the field-relevant range.
 */
export function fastCos(x: number): number {
  // 1) Reduce to [−π, π].
  let y = x - Math.round(x * INV_TWO_PI) * TWO_PI;
  // 2) Fold to [0, π/2] using cos symmetry.
  let sign = 1;
  if (y < 0) y = -y;                // cos is even
  if (y > HALF_PI) {                // cos(π − y) = −cos(y)
    y = PI - y;
    sign = -1;
  }
  // 3) Estrin polynomial in y² — balanced FMA tree the JIT can vectorise.
  const y2 = y * y;
  const y4 = y2 * y2;
  const y8 = y4 * y4;
  const p01 = C0  + C2  * y2;
  const p23 = C4  + C6  * y2;
  const p45 = C8  + C10 * y2;
  return sign * (p01 + y4 * p23 + y8 * p45);
}

/**
 * Vector cos: writes cos(angles[i]) into out[i]. Hot loop is monomorphic +
 * branch-light → the JIT vectorises to packed-double SIMD on AVX2 hosts.
 *
 * Caller guarantees `out.length >= n` and `angles.length >= n`.
 */
export function vCos(angles: Float64Array, out: Float64Array, n: number): void {
  for (let i = 0; i < n; i++) {
    const x = angles[i];
    let y = x - Math.round(x * INV_TWO_PI) * TWO_PI;
    let sign = 1;
    if (y < 0) y = -y;
    if (y > HALF_PI) { y = PI - y; sign = -1; }
    const y2 = y * y;
    const y4 = y2 * y2;
    const y8 = y4 * y4;
    const p01 = C0 + C2 * y2;
    const p23 = C4 + C6 * y2;
    const p45 = C8 + C10 * y2;
    out[i] = sign * (p01 + y4 * p23 + y8 * p45);
  }
}
