/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiOcrRouteImport } from './routes/api/ocr'
import { Route as ApiKimiRouteImport } from './routes/api/kimi'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicOmegaTrainRouteImport } from './routes/api/public/omega-train'

const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOcrRoute = ApiOcrRouteImport.update({
  id: '/api/ocr',
  path: '/api/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKimiRoute = ApiKimiRouteImport.update({
  id: '/api/kimi',
  path: '/api/kimi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOmegaTrainRoute = ApiPublicOmegaTrainRouteImport.update({
  id: '/api/public/omega-train',
  path: '/api/public/omega-train',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/kimi': typeof ApiKimiRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/public/omega-train': typeof ApiPublicOmegaTrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/kimi': typeof ApiKimiRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/public/omega-train': typeof ApiPublicOmegaTrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/kimi': typeof ApiKimiRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/public/omega-train': typeof ApiPublicOmegaTrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/api/chat'
    | '/api/kimi'
    | '/api/ocr'
    | '/api/transcribe'
    | '/api/public/omega-train'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/api/chat'
    | '/api/kimi'
    | '/api/ocr'
    | '/api/transcribe'
    | '/api/public/omega-train'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/api/chat'
    | '/api/kimi'
    | '/api/ocr'
    | '/api/transcribe'
    | '/api/public/omega-train'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiKimiRoute: typeof ApiKimiRoute
  ApiOcrRoute: typeof ApiOcrRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiPublicOmegaTrainRoute: typeof ApiPublicOmegaTrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocr': {
      id: '/api/ocr'
      path: '/api/ocr'
      fullPath: '/api/ocr'
      preLoaderRoute: typeof ApiOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kimi': {
      id: '/api/kimi'
      path: '/api/kimi'
      fullPath: '/api/kimi'
      preLoaderRoute: typeof ApiKimiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/omega-train': {
      id: '/api/public/omega-train'
      path: '/api/public/omega-train'
      fullPath: '/api/public/omega-train'
      preLoaderRoute: typeof ApiPublicOmegaTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  ApiChatRoute: ApiChatRoute,
  ApiKimiRoute: ApiKimiRoute,
  ApiOcrRoute: ApiOcrRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiPublicOmegaTrainRoute: ApiPublicOmegaTrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
